### ISSUE TITLE
翻译『组件外部跳转』

### ISSUE THREAD

**Issue by camsong** [react-guide/react-router-cn#10]
URL：https://github.com/react-guide/react-router-cn/blob/master/docs/guides/advanced/NavigatingOutsideOfComponents.md

欢迎认领，直接回复即可认领

**Comment by camsong** [comment]
标题译的不够直观，可以修改一下，这一章真实内容是『在组件外部使用 React Router 做跳转的意思』

**Comment by 4074** [comment]
我来认领~

**Comment by camsong** [comment]
@4074 :+1:

**Comment by camsong** [comment]
completed by https://github.com/react-guide/react-router-cn/pull/27
