### ISSUE TITLE
翻译『API 文档』

### ISSUE THREAD

**Issue by camsong** [react-guide/react-router-cn#11]
URL：https://github.com/react-guide/react-router-cn/blob/master/docs/API.md

欢迎认领，直接回复即可认领

**Comment by camsong** [comment]
I'll do this one

**Comment by fredxie** [comment]
If you haven't started on this I can take it.

**Comment by camsong** [comment]
@fredxie Sweet, actually I barely  have time to do this since I am busy for the Double Eleven Festival these days, great thanks for your support.
Go ahead and don't hesitate :smile:

**Comment by fredxie** [comment]
@camsong :+1: Will start real soon. Could you assign this issue to me? Thanks!

**Comment by camsong** [comment]
Sorry, that "assign" is different, GitHub can only "assign" to contributors. And we'd like to invite passionate committers to become our contributors.

Anyway, you already been literally assigned in the previous comments.

**Comment by camsong** [comment]
@fredxie How's going?

**Comment by camsong** [comment]
状态改为『待认领』

**Comment by jovey-zheng** [comment]
I'll do this.
