### ISSUE TITLE
翻译『词汇表』

### ISSUE THREAD

**Issue by camsong** [react-guide/react-router-cn#12]
URL：https://github.com/react-guide/react-router-cn/blob/master/docs/Glossary.md

欢迎认领，直接回复即可认领

**Comment by starkwang** [comment]
我可以认领这个么

**Comment by camsong** [comment]
@starkwang 这个是最难翻译的章节之一。
我们帮你做校验，相信你，加油！

**Comment by jovey-zheng** [comment]
@starkwang 加油:muscle:

**Comment by camsong** [comment]
completed https://github.com/react-guide/react-router-cn/pull/25
