### ISSUE TITLE
英文文档中的换行

### ISSUE THREAD

**Issue by yuweiw823** [react-guide/react-router-cn#16]
英文文档中的换行有误。

比如 
https://raw.githubusercontent.com/rackt/react-router/master/docs/guides/basics/Histories.md
https://raw.githubusercontent.com/rackt/react-router/master/docs/guides/basics/IndexRoutes.md
在大约75个字符处直接换行，导致一段话被拆分成到多个行。

问题：翻译后中文的行号应该如何对齐？

**Comment by jovey-zheng** [comment]
像 `Histories.md` 中的第一部分，在 `.md` 文件中是换行的，但解析为 `HTML` 时就没有了。
这个和 @camsong 讨论了下，翻译时就按 `.md` 中的行数去翻译，便于后续的**校对工作**。
第一部分的第二句话：

> In a nutshell, a history knows how to listen to the browser's address
> bar for changes and parses the URL into a `location` object that the
> router can use to match routes and render the correct set of components.

为了语句通顺，感觉没必要换行翻译，不过这里倒是应该断句，对阅读要好。（感觉官方文档是不是按多了 Enter :joy: 或者为了断句）

**Comment by camsong** [comment]
这是因为代码一般都是约定每行最多 80 个字符。当然这个约定只适用于质量高的项目。
比如给 React 提交 PR 一定要符合并个规则，否则不会被接收。
Redux 文档严格遵循这个规则，React Router 部分遵循这个规则（很可能是两个人写的）。
现在我们译时尽量行数保持与原文一致，如 @jovey-zheng 所说主要是为了以后**校对工作**。
Markdown 里敲一个 Enter 是不受影响的。

有两种情况下 Enter 会有影响
- 行尾>2个空格会解析为  `</br>`
- 空一行表示开始新段落

**Comment by yuweiw823** [comment]
好的，懂了！

**Comment by jovey-zheng** [comment]
#29

**Comment by desenmeng** [comment]
涨知识
