### ISSUE TITLE
翻译『路由配置』

### ISSUE THREAD

**Issue by camsong** [react-guide/react-router-cn#2]
Url：https://github.com/react-guide/react-router-cn/blob/master/docs/guides/basics/RouteConfiguration.md

这一章相关内容比较多

**Comment by camsong** [comment]
@demohi 有时间吗？

**Comment by desenmeng** [comment]
@camsong :ok_hand:

**Comment by desenmeng** [comment]
#15 第一版粗翻完成
- 各位帮忙校对
- `Preserving URLs` 不知如何翻译比较准确
- 为了方便校对，还保留了英文
