### ISSUE TITLE
翻译『默认路由（IndexRoute）与 IndexLink』

### ISSUE THREAD

**Issue by camsong** [react-guide/react-router-cn#5]
Url：https://github.com/react-guide/react-router-cn/blob/master/docs/guides/basics/IndexRoutes.md

**Comment by camsong** [comment]
@yuweiw823 assign 给你啦 :cake:

**Comment by yuweiw823** [comment]
No problem :)

On Mon, Oct 19, 2015 at 11:32 PM, Cam Song notifications@github.com wrote:

> Assigned #5 https://github.com/react-guide/react-router-cn/issues/5 to
> @yuweiw823 https://github.com/yuweiw823.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/react-guide/react-router-cn/issues/5#event-439966916.

## 

_Yuwei WANG_
Software Developer
University of Washington
yuweiw823@gmail.com | (206) 941-4907 | www.yuwei-vera.com

**Comment by camsong** [comment]
completed by https://github.com/react-guide/react-router-cn/pull/18
