### ISSUE TITLE
翻译『动态路由』

### ISSUE THREAD

**Issue by camsong** [react-guide/react-router-cn#6]
URL: https://github.com/react-guide/react-router-cn/blob/master/docs/guides/advanced/DynamicRouting.md

欢迎认领，直接回复即可认领

**Comment by guocheng** [comment]
我来认领吧

**Comment by camsong** [comment]
@guocheng :+1:

**Comment by camsong** [comment]
@guocheng any update on this?

**Comment by camsong** [comment]
completed by https://github.com/react-guide/react-router-cn/pull/21/
