### ISSUE TITLE
翻译『模块生命周期』

### ISSUE THREAD

**Issue by camsong** [react-guide/react-router-cn#9]
URL：https://github.com/react-guide/react-router-cn/blob/master/docs/guides/advanced/ComponentLifecycle.md

欢迎认领，直接回复即可认领

**Comment by camsong** [comment]
@demohi for u :muscle:

**Comment by desenmeng** [comment]
:ok_hand:

**Comment by desenmeng** [comment]
https://github.com/react-guide/react-router-cn/pull/29
